language: ruby
sudo: required
dist: trusty
services: docker
install: bundle install
cache: bundler
before_script: sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
script: travis_wait 30 kitchen converge -c2 --color -l info
branches:
  only:
    - master
    - develop
notifications:
  email:
    - pj@ezgr.net
